# Generated by Django 3.0.5 on 2020-04-19 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcf', '0002_auto_20200419_0852'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField(null=True)),
                ('description', models.CharField(max_length=300, null=True)),
            ],
        ),
    ]
