# Generated by Django 3.0.5 on 2020-04-19 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcf', '0005_auto_20200419_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='nickname',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
