# Generated by Django 3.0.5 on 2020-04-26 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcf', '0008_auto_20200419_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='games',
            field=models.ManyToManyField(to='gcf.Game'),
        ),
    ]
