# Generated by Django 3.0.5 on 2020-04-27 20:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gcf', '0009_player_games'),
    ]

    operations = [
        migrations.CreateModel(
            name='MouseConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dpi', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gcf.Game')),
                ('mouse_config', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gcf.MouseConfig')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gcf.Player')),
            ],
        ),
    ]
