# Generated by Django 3.0.5 on 2020-04-28 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gcf', '0010_mouseconfig_playerconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerconfig',
            name='mouse_config',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='gcf.MouseConfig'),
        ),
    ]
