# Generated by Django 3.0.5 on 2020-05-01 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gcf', '0011_auto_20200428_1557'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrosshairConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crosshair_avg_settings', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StartUpSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startup_avg_settings', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VideoConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resolution_width', models.IntegerField(null=True)),
                ('resolution_height', models.IntegerField(null=True)),
                ('aspect_ration_width', models.IntegerField(null=True)),
                ('aspect_ration_height', models.IntegerField(null=True)),
                ('frequency', models.IntegerField(null=True)),
                ('dimension', models.IntegerField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='mouseconfig',
            name='edpi',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='mouseconfig',
            name='game_sens',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='mouseconfig',
            name='raw_input',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='mouseconfig',
            name='usb_rate',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='mouseconfig',
            name='win_sens',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='mouseconfig',
            name='zoom_sens',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='steam_link',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='twitch_link',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='playerconfig',
            name='mouse_config',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gcf.MouseConfig'),
        ),
        migrations.AlterUniqueTogether(
            name='playerconfig',
            unique_together={('game', 'player')},
        ),
    ]
