# Generated by Django 3.0.5 on 2020-05-01 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcf', '0013_auto_20200501_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='mouseconfig',
            name='mouse_acceleration',
            field=models.FloatField(null=True),
        ),
    ]
