# Generated by Django 3.0.5 on 2020-05-01 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcf', '0014_mouseconfig_mouse_acceleration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoconfig',
            name='dimension',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
