# Generated by Django 3.0.5 on 2020-05-03 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gcf', '0015_auto_20200501_1316'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('nickname', models.CharField(max_length=100, unique=True)),
                ('age', models.IntegerField(null=True)),
                ('city', models.CharField(max_length=100, null=True)),
                ('steam_link', models.CharField(max_length=300, null=True)),
                ('twitch_link', models.CharField(max_length=300, null=True)),
                ('description', models.CharField(max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ViewModelConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewmodel_settings', models.TextField(null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='crosshairconfig',
            old_name='crosshair_avg_settings',
            new_name='crosshair_settings',
        ),
        migrations.RemoveField(
            model_name='player',
            name='age',
        ),
        migrations.RemoveField(
            model_name='player',
            name='city',
        ),
        migrations.RemoveField(
            model_name='player',
            name='description',
        ),
        migrations.RemoveField(
            model_name='player',
            name='name',
        ),
        migrations.RemoveField(
            model_name='player',
            name='nickname',
        ),
        migrations.RemoveField(
            model_name='player',
            name='steam_link',
        ),
        migrations.RemoveField(
            model_name='player',
            name='twitch_link',
        ),
        migrations.AddField(
            model_name='player',
            name='info',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gcf.PlayerInfo'),
        ),
        migrations.AddField(
            model_name='playerconfig',
            name='viewmodel_config',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gcf.ViewModelConfig'),
        ),
    ]
