# Generated by Django 3.0.5 on 2020-05-03 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcf', '0016_auto_20200503_1209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerinfo',
            name='nickname',
        ),
        migrations.AddField(
            model_name='player',
            name='nickname',
            field=models.CharField(default='s1mple', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='playerinfo',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
