# Generated by Django 3.0.5 on 2020-05-03 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gcf', '0018_auto_20200503_1534'),
    ]

    operations = [
        migrations.RenameField(
            model_name='startupsettings',
            old_name='startup_avg_settings',
            new_name='startup_settings',
        ),
    ]
