# Generated by Django 3.0.5 on 2020-05-04 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gcf', '0020_playerstats'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=300, null=True)),
                ('hltv_picture', models.CharField(max_length=300, null=True)),
                ('hltv_crop_picture', models.CharField(max_length=300, null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gcf.Player')),
            ],
        ),
    ]
